### 1) Check the version of pandas and numpy installed using the following commands:
import numpy; print (numpy.version.version) #numpy version\

import pandas as pd; print (pd.__version__) #numpy version

In [1]:
import numpy as np
print(np.__version__)

1.24.3


In [2]:
import pandas as pd
print(pd.__version__)

2.0.3


### 2) Write a program to print 'Hello HCIA PDTP-Huawei Team'

In [3]:
print("Hello HCIA PDTP-Huawei Team")

Hello HCIA PDTP-Huawei Team


### 3) Write a program to define two variables, calculate their sum and display the results

In [4]:
a = 9
b = 8
print(a+b)

17


### 4)
a) Write a program to define a tuple that contains only one element.

b) Write a program to define a tuple and then use the 'for loop' to print all the elements.

In [5]:
mytuple = ("apple",)
print(type(mytuple))

<class 'tuple'>


In [6]:
mytuple = ("apple", "banana", "cherry", "orange")
for x in mytuple:
    print(x)

apple
banana
cherry
orange


### 5) Write code to create a Python dictionary (the dict type) and print out the details. Add two entries to the dictionary: Associate the key ‘name’ with the value ‘Reagan’, and associate the key ‘phone’ with ‘+254 722 222333’

In [7]:
mydict = {
    "name": "Reagan",
    "phone": "+254712345678"
}
print(mydict)

{'name': 'Reagan', 'phone': '+254712345678'}


### 6) a) Define a function to do Multiplication, such as Mul(8,6),and it output 42.

b) Complete the function definition so it returns the square of the product of the parameters, so sqrProd(2, 5) returns (2*5)*(2*5) = 100.
def sqrProd(x, y):

In [10]:
def application(a,b):
    return a*b
print(application(5,6))

30


In [12]:
def sqrProd(x,y):
    return x*y * x*y
print(sqrProd(2,5))

100


### 7) Import numpy and then:
a) Use numpy to define an array, the shape of it is (5,5) and all elements of it is 0.

b) Create a 3x3 matrix with values ranging from 0 to 8

c) Find indices of non-zero elements from [1,2,0,0,4,0]

d) Create a 10x10 array with random values and find the minimum and maximum values

e) Create a random vector of size 30 and find the mean value

In [20]:
import numpy as np
myArray = np.array([[0,0,0,0,0], [0,0,0,0,0], [0,0,0,0,0], [0,0,0,0,0], [0,0,0,0,0]])
print(np.array(myArray).shape)
print(myArray)


(5, 5)
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [25]:
import numpy as np
matrix = np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [27]:
import numpy as np

array = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(array)

print(indices)

(array([0, 1, 4], dtype=int64),)


In [32]:
import numpy as np

array = np.random.rand(10,10)
print(array)


minimum_value = np.min(array)
maximum_value = np.max(array)

print("Minimum value:", minimum_value)
print("Maximum value:", maximum_value)

[[0.99674067 0.37529193 0.90407425 0.88014156 0.67597271 0.49647021
  0.55537527 0.25948301 0.65136684 0.77784077]
 [0.99446164 0.4842941  0.96154632 0.11270231 0.40752695 0.8994528
  0.59652466 0.72333797 0.53781906 0.27521589]
 [0.80864808 0.20981306 0.99158881 0.20732492 0.0994449  0.44633276
  0.66340073 0.17863265 0.81697962 0.30644068]
 [0.63554083 0.85827994 0.31966071 0.85461124 0.43145173 0.52371608
  0.31016182 0.55766969 0.89473933 0.13465459]
 [0.10721975 0.14935828 0.64395974 0.24706052 0.1316062  0.27086367
  0.47750296 0.65480014 0.92537397 0.03969494]
 [0.02208194 0.27518537 0.72251859 0.07032032 0.06555023 0.24480965
  0.48709389 0.19889159 0.94961579 0.63548976]
 [0.75835441 0.49320101 0.43769423 0.84318475 0.48571895 0.34724655
  0.54616522 0.49371574 0.52349038 0.08777669]
 [0.29830488 0.54333091 0.30911651 0.44457557 0.45438198 0.3848512
  0.60617203 0.35925183 0.09644006 0.1052921 ]
 [0.5261741  0.44294172 0.81039832 0.30179801 0.44750705 0.06445552
  0.76151322 0

In [29]:
import numpy as np

random_vector = np.random.rand(30)
mean_value = np.mean(random_vector)

print("Random Vector:", random_vector)
print("Mean Value:", mean_value)

Random Vector: [0.70802088 0.97689473 0.84301277 0.68654887 0.75686886 0.93511292
 0.06280791 0.8849791  0.31312331 0.04229269 0.11316541 0.41837826
 0.14536469 0.82875869 0.64966742 0.91705564 0.30999533 0.6769905
 0.19152169 0.42794259 0.04135355 0.93351901 0.89817278 0.36195256
 0.82600907 0.35969122 0.84626895 0.3408726  0.50618291 0.23460516]
Mean Value: 0.5412376689743004


### 8) Write a Python program that prompts the user for two numbers, reads them in, and prints out the product, labeled appropriately.

In [35]:
import numpy as np
product = np.prod([int(input("Enter a number: ")), int(input("Enter another number: "))])
print(product)


42


### 9) Complete the code for the following function so it matches its documentation:
def doubleList(numberList):

For each of the numbers in the list numberList, print a line containing twice the original
number. For example, doubleList ([3, 1, 5]) would print 6, 2, 10

In [39]:
def doubleList(numberList):
    for number in numberList:
        print(number * 2)
doubleList([3, 1, 5])

6
2
10
